# Generated by Django 4.2.25 on 2026-01-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajecontacto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Mensaje de contacto', 'verbose_name_plural': 'Mensajes de contacto'},
        ),
        migrations.RenameField(
            model_name='mensajecontacto',
            old_name='fecha_envio',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
