# Generated by Django 4.2.25 on 2025-10-24 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_productos_precio_sin_iva_alter_productos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.categoriaproducto', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='disponibilidad',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
