# Generated by Django 4.2.25 on 2025-10-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_productos_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
