# Generated by Django 4.2.25 on 2025-10-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_respuesta',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Respuesta Redsys'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descripcion_error',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción Error'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_intento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Intento Pago'),
        ),
    ]
