# Generated by Django 4.2.25 on 2025-10-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_pedido_enviado_pedido_fecha_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='envio_gratis',
            field=models.BooleanField(default=False, verbose_name='Envío gratis'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='gastos_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gastos de envío'),
        ),
    ]
