# Generated by Django 4.2.25 on 2025-10-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_pedido_envio_gratis_pedido_gastos_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_envio_gratis', models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='Umbral para envío gratis (€)')),
                ('costo_envio_estandar', models.DecimalField(decimal_places=2, default=5.95, max_digits=10, verbose_name='Costo envío estándar (€)')),
                ('activo', models.BooleanField(default=True, verbose_name='Configuración activa')),
            ],
            options={
                'verbose_name': 'configuración de envío',
                'verbose_name_plural': 'configuraciones de envío',
            },
        ),
    ]
