# Generated by Django 4.2.25 on 2026-04-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='destacado_en_index',
            field=models.BooleanField(default=False, verbose_name='Mostrar en galería del index'),
        ),
    ]
