# Generated by Django 4.2.25 on 2025-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contenido',
        ),
        migrations.AddField(
            model_name='post',
            name='contenido_espanol',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='contenido_ingles',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
