# Generated by Django 4.2.25 on 2026-03-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
