# Generated by Django 4.2.25 on 2026-01-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_contenido_post_contenido_espanol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.AddField(
            model_name='post',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(related_name='posts', to='blog.categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido_ingles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
