# Generated by Django 4.2.25 on 2025-10-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('cif', models.CharField(blank=True, max_length=20, null=True)),
                ('provincia', models.CharField(max_length=30)),
                ('localidad', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=150)),
                ('numero_calle', models.CharField(max_length=3)),
                ('portal', models.CharField(blank=True, max_length=3)),
                ('escalera', models.CharField(blank=True, max_length=3)),
                ('piso', models.CharField(max_length=3)),
                ('puerta', models.CharField(max_length=3)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('antiguedad_cliente', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('reset_token_expiration', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
